# File: pubspec.yaml

name: bugbear_app
description: "A visionary Flutter project, built with passion and innovative flair."

publish_to: 'none'
version: 1.0.0+1

environment:
  # Must match the Dart runtime shipped with Flutter 3.7.2 (Dart 2.19.2)
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  http: ^1.3.0
  audioplayers: ^6.4.0
  intl: ^0.19.0
  timezone: ^0.10.0
  flutter_local_notifications: ^19.1.0
  provider: ^6.0.5
  json_annotation: ^4.8.1       # downgraded to support Dart <3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  firebase_auth_mocks: ^0.14.1
  build_runner: ^2.4.6
  json_serializable: ^6.5.0    # downgraded to match json_annotation
  intl_utils: ^2.8.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fragen_de.json
    - assets/fragen_en.json
    - assets/images/
    - assets/sounds/

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
