name: bugbear_app
description: "A visionary Flutter project, built with passion and innovative flair."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  http: ^1.3.0
  audioplayers: ^6.4.0
  intl: ^0.19.0
  timezone: ^0.10.0
  flutter_local_notifications: ^19.1.0
  provider: ^6.0.5
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  cloud_firestore: ^5.6.5
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  firebase_auth_mocks: ^0.14.1
  build_runner: ^2.4.6
  json_serializable: ^6.6.0
  intl_utils: ^2.8.10

flutter:
  generate: true
  uses-material-design: true

  assets:
    # Quiz-Daten pro Locale
    - assets/quiz_questions_de.json
    - assets/quiz_questions_en.json
    - assets/reflex_categories_de.json
    - assets/reflex_categories_en.json

    # Bilder
    - assets/images/

    # Sounds
    - assets/sounds/

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
