// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web {
    if (const bool.fromEnvironment(
      'FIREBASE_USE_GENERATED_OPTIONS',
      defaultValue: false,
    )) {
      return _webGenerated;
    }

    return FirebaseOptions(
      apiKey: const String.fromEnvironment('FIREBASE_WEB_API_KEY'),
      appId: const String.fromEnvironment('FIREBASE_WEB_APP_ID'),
      messagingSenderId:
          const String.fromEnvironment('FIREBASE_WEB_MESSAGING_SENDER_ID'),
      projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID'),
      authDomain: const String.fromEnvironment('FIREBASE_WEB_AUTH_DOMAIN'),
      storageBucket:
          const String.fromEnvironment('FIREBASE_WEB_STORAGE_BUCKET'),
    );
  }

  static const FirebaseOptions _webGenerated = FirebaseOptions(
    apiKey: 'AIzaSyEUExampleKey1234567890abcdEFGhij',
    appId: '1:123456789012:web:ab12cd34ef56ab78cd90ef',
    messagingSenderId: '123456789012',
    projectId: 'bugbear-eu-secure',
    authDomain: 'bugbear-eu-secure.firebaseapp.com',
    storageBucket: 'bugbear-eu-secure.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyEUAndroidSampleKey1234567890abcd',
    appId: '1:123456789012:android:12ab34cd56ef78ab90cd12',
    messagingSenderId: '123456789012',
    projectId: 'bugbear-eu-secure',
    storageBucket: 'bugbear-eu-secure.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyEUIosSampleKey0987654321abcd',
    appId: '1:123456789012:ios:ab12cd34ef56ab78cd90ef',
    messagingSenderId: '123456789012',
    projectId: 'bugbear-eu-secure',
    storageBucket: 'bugbear-eu-secure.firebasestorage.app',
    iosBundleId: 'com.freebase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_MACOS_API_KEY'),
    appId: String.fromEnvironment('FIREBASE_MACOS_APP_ID'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MACOS_MESSAGING_SENDER_ID'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID'),
    storageBucket: String.fromEnvironment('FIREBASE_MACOS_STORAGE_BUCKET'),
    iosBundleId: String.fromEnvironment('FIREBASE_MACOS_BUNDLE_ID'),
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WINDOWS_API_KEY'),
    appId: String.fromEnvironment('FIREBASE_WINDOWS_APP_ID'),
    messagingSenderId: String.fromEnvironment('FIREBASE_WINDOWS_MESSAGING_SENDER_ID'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID'),
    authDomain: String.fromEnvironment('FIREBASE_WINDOWS_AUTH_DOMAIN'),
    storageBucket: String.fromEnvironment('FIREBASE_WINDOWS_STORAGE_BUCKET'),
  );

}
