name: build

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.2'

      - name: Cache Pub Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Auto-format code
        run: flutter format --set-exit-if-changed .

      - name: Analyze Project
        run: flutter analyze

      # ----------------------------------------------------------------------------
      # Temporarily disabled until red-screen errors are fixed:
      # ----------------------------------------------------------------------------
      # - name: Run Tests & Gather Coverage
      #   run: flutter test --coverage
      # ----------------------------------------------------------------------------

      - name: Upload Coverage
        if: false
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/lcov.info

      - name: Post Cache Pub Dependencies
        if: ${{ always() }}
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}

      # (Optional) if you really want to cache the Flutter SDK, uncomment and
      # hard-code your version rather than use matrix:
      #
      # - name: Cache Flutter SDK
      #   if: ${{ always() }}
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.flutter
      #     key: ${{ runner.os }}-flutter-3.7.2
